//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMI_SP.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMI_SP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;MMI&gt;
        ///  &lt;Strings&gt;
        ///    &lt;Common&gt;
        ///      &lt;Empty&gt;Empty&lt;/Empty&gt;
        ///    &lt;/Common&gt;
        ///    &lt;Update&gt;
        ///      &lt;UpdateAvailable&gt;Update available!&lt;/UpdateAvailable&gt;
        ///      &lt;UpdateText&gt;A new version of Mors Mutual Insurance Single Player is available!&lt;/UpdateText&gt;
        ///    &lt;/Update&gt;
        ///    &lt;Agency&gt;
        ///      &lt;AgencyEntry&gt;Press ~INPUT_CONTEXT~ to enter.&lt;/AgencyEntry&gt;
        ///      &lt;AgencyEntryWanted&gt;You cannot enter the building while wanted.&lt;/AgencyEntryWanted&gt;
        ///    &lt;/Agency&gt;
        ///    &lt;Menus&gt;
        ///      &lt;!- [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner {
            get {
                object obj = ResourceManager.GetObject("banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [GENERAL]
        ///LANGUAGE = default
        ///PERSISTENTINSUREDVEHICLES = True
        ///
        ///[CHECK]
        ///CHECKFORUPDATE = true
        ///SHOWSHVDNNOTIFICATION = true
        ///SHOWFILENOTIFICATION = true
        ///SHOWVISUALCNOTIFICATION = true
        ///SHOWNETFRAMEWORKNOTIFICATION = true
        ///
        ///[INSURANCE]
        ///INSURANCECOSTMULTIPLIER = 1
        ///RECOVERCOSTMULTIPLIER = 1
        ///STOLENCOSTMULTIPLIER = 5
        ///
        ///[BRINGVEHICLE]
        ///BRINGVEHICLEBASEPRICE = 200
        ///BRINGVEHICLEINSTANT = False
        ///BRINGVEHICLETIMEOUT = 2
        ///BRINGVEHICLERADIUS = 100
        ///
        ///[IFRUIT]
        ///PHONEVOLUME = 25
        ///CaniFruitInsure = false
        ///CaniFr [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream End_ByeNow {
            get {
                return ResourceManager.GetStream("End_ByeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream End_DriveSafe {
            get {
                return ResourceManager.GetStream("End_DriveSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream End_NiceDay {
            get {
                return ResourceManager.GetStream("End_NiceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream End_NiveDay2 {
            get {
                return ResourceManager.GetStream("End_NiveDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream End_SoLong {
            get {
                return ResourceManager.GetStream("End_SoLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream End_StaySafe {
            get {
                return ResourceManager.GetStream("End_StaySafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap insurance {
            get {
                object obj = ResourceManager.GetObject("insurance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Mid_ICanDoThat {
            get {
                return ResourceManager.GetStream("Mid_ICanDoThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Mid_ILookIntoit {
            get {
                return ResourceManager.GetStream("Mid_ILookIntoit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Mid_IWillDoMyBest {
            get {
                return ResourceManager.GetStream("Mid_IWillDoMyBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Mid_Okay {
            get {
                return ResourceManager.GetStream("Mid_Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Mid_Sure {
            get {
                return ResourceManager.GetStream("Mid_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Mid_WeCanDoThat {
            get {
                return ResourceManager.GetStream("Mid_WeCanDoThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Mid_WeCanHandleThat {
            get {
                return ResourceManager.GetStream("Mid_WeCanHandleThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream NoMoney {
            get {
                return ResourceManager.GetStream("NoMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Start_HelloThisIsMMI {
            get {
                return ResourceManager.GetStream("Start_HelloThisIsMMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Start_MMIExpectUnexpected {
            get {
                return ResourceManager.GetStream("Start_MMIExpectUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Start_MMIHereToHelp {
            get {
                return ResourceManager.GetStream("Start_MMIHereToHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Start_MMIHowCanHelp {
            get {
                return ResourceManager.GetStream("Start_MMIHowCanHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Start_MMIHowCanIBeService {
            get {
                return ResourceManager.GetStream("Start_MMIHowCanIBeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Start_MMIPeaceOfMind {
            get {
                return ResourceManager.GetStream("Start_MMIPeaceOfMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Start_MMITrust {
            get {
                return ResourceManager.GetStream("Start_MMITrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Start_WhatCanIDo {
            get {
                return ResourceManager.GetStream("Start_WhatCanIDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Start_WhatCanIHelpYouWith {
            get {
                return ResourceManager.GetStream("Start_WhatCanIHelpYouWith", resourceCulture);
            }
        }
    }
}
